version: '3'

services:
  nginx:
    container_name: nginx_1
    restart: unless-stopped
    image: nginx:stable-alpine
    volumes:
      - ./static-html:/usr/share/nginx/html
    ports:
      - "80:80"

networks:
  default:
    external:
      name:
        web_network_nginx